name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Configurar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Backend - Instalar dependencias
      working-directory: ./Backend
      run: npm ci

    - name: Backend - Ejecutar tests
      working-directory: ./Backend
      run: npm test

    - name: Frontend - Instalar dependencias
      working-directory: ./Frontend
      run: npm ci

    - name: Frontend - Build
      working-directory: ./Frontend
      run: npm run build --if-present

    - name: Frontend - Ejecutar tests
      working-directory: ./Frontend
      run: npm test 